import Head from 'next/head'
import Image from 'next/image'
import { ToastContainer, toast } from 'react-toastify'
import productDesktopImg from 'assets/images/image-product-desktop.jpg'
import cart from 'assets/images/icon-cart.svg'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Product Preview Card</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          src={productDesktopImg}
          alt="product desktop"
          className={styles.desktopImg}
          objectFit="cover"
        />

        <section className={styles.productInfoSection}>
          <div className={styles.type}>Perfume</div>
          <h2 className={styles.productHeading}>Gabrielle Essence Eau De Parfum</h2>
          <p className={styles.description}>
            A floral, solar and voluptuous interpretation composed by Olivier Polge,
            Perfumer-Creator for the House of CHANEL
          </p>
          <div className={styles.priceWrapper}>
            <div className={styles.price}>$149.99</div>
            <div className={styles.discounted}>$169.99</div>
          </div>

          <button className={styles.cartBtn} onClick={() => toast.success('Item added')}>
            <Image src={cart} alt="cart" />
            <div className={styles.btnText}>Add to Cart</div>
          </button>
        </section>
      </main>

      <ToastContainer position="top-center" pauseOnHover={false} theme="colored" />
    </div>
  )
}
